# Generated by Django 4.2 on 2023-10-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_authenticated',
        ),
    ]
