# Generated by Django 4.2 on 2023-10-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_user_otp_user_otp_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
